"""Init

Revision ID: 0c1abeeb5a6d
Revises: 5ad6819a4a1e
Create Date: 2022-09-13 16:44:24.846278

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c1abeeb5a6d'
down_revision = '5ad6819a4a1e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
