"""Init new table

Revision ID: 5ad6819a4a1e
Revises: 
Create Date: 2022-09-13 13:00:00.706623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ad6819a4a1e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posthead',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.Column('creation_date', sa.String(length=20), nullable=True),
    sa.Column('price', sa.String(length=255), nullable=True),
    sa.Column('currency', sa.String(length=2), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('beds_count', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('posthead')
    # ### end Alembic commands ###
