"""Init new table

Revision ID: b559eb15d488
Revises: 0c1abeeb5a6d
Create Date: 2022-09-13 16:45:17.723568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b559eb15d488'
down_revision = '0c1abeeb5a6d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
